Update prometheus_exporter to work with airflow 2
jampp/airflow-prometheus-exporter pull request #9
Opened 2022-05-16 15:29 UTC by Rcharriol

2022-05-16 15:53 UTC, gonzalezzfelipe requested changes

2022-05-16 15:53 UTC, gonzalezzfelipe commented on airflow_prometheus_exporter/prometheus_exporter.py
> +                        DagRun.execution_date
I find this weird, especially because you are not querying that table 🤔

2022-05-16 15:53 UTC, gonzalezzfelipe commented on airflow_prometheus_exporter/prometheus_exporter.py
> +        # yield task_duration
Lets delete it if we are not using it, we can always go back to the git history

2022-05-16 15:53 UTC, gonzalezzfelipe commented on airflow_prometheus_exporter/prometheus_exporter.py
> +        #     labels=["dag_id"],
Same here

2022-05-16 15:53 UTC, gonzalezzfelipe commented on airflow_prometheus_exporter/prometheus_exporter.py
> +from flask_appbuilder import BaseView as FABBaseView, expose as FABexpose
Why is this not on the top?

2022-05-16 15:56 UTC, Rcharriol commented on airflow_prometheus_exporter/prometheus_exporter.py
> +                        DagRun.execution_date
I had issues with this, yes is weird, this is one of the changes for airflow2 compatibility.
I will see to fix it

2022-05-16 15:57 UTC, Rcharriol commented on airflow_prometheus_exporter/prometheus_exporter.py
> +        # yield task_duration
Yep, i commented it on prd, a day, and stayed like that until today

2022-05-16 15:57 UTC, Rcharriol commented on airflow_prometheus_exporter/prometheus_exporter.py
> +from flask_appbuilder import BaseView as FABBaseView, expose as FABexpose
I could ask the original creator about that
But i will just change it 😜

2022-05-17 15:09 UTC, gonzalezzfelipe approved these changes

2022-05-17 17:32 UTC, merged